### ISSUE TITLE
Association documentation model case sensitivity issue

### ISSUE THREAD

**Issue by bradisbell** [domasx2/sequelize-fixtures#25]
The documentation for association seems to be incorrect.  This is what is in the readme:

```json
[
    {
        "model": "Owner",
        "data": {
            "name": "John Doe",
            "city": "Vilnius"
        }
    },
    {
        "model": "Car",
        "data": {
            "make": "Ford",
            "owner": { //make sure it's unique across all owners
                "name": "John Doe" 
            }
        }
    }
]
```

`owner` should really be `Owner` to match the model name.

```json
[
    {
        "model": "Owner",
        "data": {
            "name": "John Doe",
            "city": "Vilnius"
        }
    },
    {
        "model": "Car",
        "data": {
            "make": "Ford",
            "Owner": { //make sure it's unique across all owners
                "name": "John Doe" 
            }
        }
    }
]
```

**Comment by domasx2** [comment]
Hi, this is deliberate due to naming conventions used.

I use camel-case for class (and model) names in javascript, so it's models.Owner,
but lowercase underscored table names in the databse, so owner model would be defined as:

```javascript
sequelize.define("owner", {...});
```

Keys in the data object map to propeprty keys on the sequelize entity, wether explicitly defined or created by sequelize to hold associations.  The association property matches name passed to sequelize.define and thus is "owner".

I can see how this is confusing without an explanation :)
